name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Example tests
        run: |
          cd example
          sbt test
          cd ../
      - name: Run Week1 Exercise tests
        run: |
          cd recfun
          sbt test
          cd ../
      - name: Run Week2 Exercise tests
        run: |
          cd funsets
          sbt test
          cd ../